### ISSUE TITLE
ES logs are crazy

### ISSUE THREAD

**Issue by TheDadycool** [couchbaselabs/elasticsearch-transport-couchbase#110]
Hi,

I'm trying to use ES 2.1.1 for a new project with CB 4.1. We are trying to use ES for indexing our CB. We are in a model where multiple Bucket in CB are sync with XCDR to one index. We don't know if this is supported.
During the test, multiple time we have seen the log file of ES increasing really quickly until filling the full drive in few minutes (30 GB logs generated). one common error in our log is : 

[2016-01-17 23:03:11,646][WARN ][org.eclipse.jetty.servlet.ServletHandler] /pools/default/buckets
NoShardAvailableActionException[No shard available for [get [couchbase][couchbaseCheckpoint][bucketUUID]: routing [null]]]; nested: RemoteTransportException[[Slab][search-dev.nayaservices.com/127.0.0.1:9300][indices:data/read/get[s]]]; nested: IndexNotFoundException[no such index];
    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.perform(TransportSingleShardAction.java:199)
    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.onFailure(TransportSingleShardAction.java:186)
    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction.access$1400(TransportSingleShardAction.java:115)
    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleException(TransportSingleShardAction.java:240)
    at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
    at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
    at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[Slab][search-dev.nayaservices.com/127.0.0.1:9300][indices:data/read/get[s]]]; nested: IndexNotFoundException[no such index];
Caused by: [couchbase] IndexNotFoundException[no such index]
    at org.elasticsearch.indices.IndicesService.indexServiceSafe(IndicesService.java:310)
    at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:94)
    at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:44)
    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:282)
    at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$ShardTransportHandler.messageReceived(TransportSingleShardAction.java:275)
    at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

I d'ont know if this one is relevant.

Thanks a lot for your help.

**Comment by chester89** [comment]
That happens for us too, only we use CB 4.0 + ES 1.7 - in case we send docs with incorrect mapping, the amount of storage logs consume goes through the roof (20 GB in an hour on one node, if not more). 
Any way to configure this?

**Comment by WillGardella** [comment]
Not saying there's not another problem here, but you might consider configuring the ES logrotate function to prevent ballooning logs. This is described for the 1.4 version of ES (here)[http://stackoverflow.com/questions/28696069/elasticsearch-how-to-configure-logging-yml].  

You can configure the verbosity of the Couchbase Transport Plugin by following the instructions [at the end of the page here](http://developer.couchbase.com/documentation/server/4.0/connectors/elasticsearch-2.1/trouble-intro.html)

**Comment by Branor** [comment]
I'm going to dig into this some more. The plugin wasn't really written with replicating multiple buckets to a single ES index in mind. Document keys are unique per bucket/index, so combining documents from multiple buckets into a single index opens the door to all sorts of data integrity issues. I suspect the two replications may be overwriting each other's checkpoint metadata. 

For now, are you able to set up a 1 to 1 bucket to index replication? You can query multiple indexes in ES to get the same combined results you're seeing with a single index now.

**Comment by TheDadycool** [comment]
This is what i have done so far, i have made a 1 -1 index to cb. Everything is working correctly. With the exception of the process goxdcr who go very up in memory consumption.

**Comment by chester89** [comment]
Thanks. Haven't check that process memory consumption, will do

2016-01-27 19:35 GMT+03:00 TheDadycool <notifications@github.com>:

> This is what i have done so far, i have made a 1 -1 index to cb.
> Everything is working correctly. With the exception of the process goxdcr
> who go very up in memory consumption.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/couchbaselabs/elasticsearch-transport-couchbase/issues/110#issuecomment-175731148>
> .
>



-- 
Yours faithfully,
Gleb

**Comment by dnault** [comment]
Hi, just doing some housekeeping on inactive issues. Okay to close this one?

**Comment by dnault** [comment]
Closing due to inactivity. Please let me know if the issue remains.
