### ISSUE TITLE
Package 2.2.1.2 Fails es to Start

### ISSUE THREAD

**Issue by miridfd** [couchbaselabs/elasticsearch-transport-couchbase#111]
Hello,

I've installed the plugin form here:
https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.2.1.2/elasticsearch-transport-couchbase-2.2.1.2.zip

also configured the java.security file as described under the "Java Security Policy Permissions" section, but on elasticsearch start I get the following exception:
Starting elasticsearch: Exception in thread "main" BindHttpException[Failed to bind to [9091]]; nested: AccessControlException[access denied ("javax.security.auth.AuthPermission" "modifyPrincipals")];
Likely root cause: java.security.AccessControlException: access denied ("javax.security.auth.AuthPermission" "modifyPrincipals")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:884)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at javax.security.auth.Subject$SecureSet.add(Subject.java:1110)
        at java.util.Collections$SynchronizedCollection.add(Collections.java:2035)
        at org.eclipse.jetty.security.MappedLoginService.putUser(MappedLoginService.java:185)
        at com.couchbase.capi.CAPIServer.basicAuth(CAPIServer.java:142)
        at com.couchbase.capi.CAPIServer.<init>(CAPIServer.java:74)
        at org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl$1$1.run(CouchbaseCAPITransportImpl.java:221)
        at org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl$1$1.run(CouchbaseCAPITransportImpl.java:217)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl$1.onPortNumber(CouchbaseCAPITransportImpl.java:217)
        at org.elasticsearch.common.transport.PortsRange.iterate(PortsRange.java:58)
        at org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl.doStart(CouchbaseCAPITransportImpl.java:214)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
        at org.elasticsearch.transport.couchbase.CouchbaseCAPI.doStart(CouchbaseCAPI.java:42)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
        at org.elasticsearch.node.Node.start(Node.java:242)
        at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:221)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:287)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

Please advice, thanks

**Comment by alexunil** [comment]
Same Problem here on a RHEL 7.2 with elasticsearch2.2.2-1.
Checked the java.security many times, its like described.

Is there an older Version without this problem? Can not find a link to an older zip-file.
Thanks,
Alex

**Comment by Branor** [comment]
This often happens when the java runtime you're using is using a different policy file from the one you edited, or you have multiple runtimes installed and ES uses a different one from what you expect. Could you please check which JRE (or JDK) ES actually loads with? And do you have a user policy file in addition to the system one? It's usually located in `${user.home}\java.policy`.

Unfortunately, an older version of the plugin won't help you if you're using ES 2.1.1, because they are now version-specific to ES, due to the way plugin security works in 2.x.

**Comment by alexunil** [comment]
Thanks very much Branor. 
Yes there is a java.policy and i added the same as in the java.security - now elasticsearch is starting again! Resolved for me

**Comment by miridfd** [comment]
Works for me as well.
Thanks.
