### ISSUE TITLE
Revenge of the modifyPrinciples error

### ISSUE THREAD

**Issue by erik-etops** [couchbaselabs/elasticsearch-transport-couchbase#121]
How am I screwing this up?

Ok so I made the change to the file $JAVA_HOME/lib/security/java.security per the README. 

Currently, the readme says:

> In order to get the plugin to work with ES 2.1.x, it is necessary to edit the system's default java.security file, which is located in the %JAVA_HOME%/jre/lib/security directory.

That was a bust, and I found a discussion in the closed issues that discuss using java.policy file to change this instead. Great. Changed that instead and put this at the end: 

```
tail $JAVA_HOME/lib/security/java.policy
};

grant codeBase "file:/usr/share/elasticsearch/plugins/transport-couchbase/*" {
  permission javax.security.auth.AuthPermission "modifyPrincipals";
  permission javax.security.auth.AuthPermission "modifyPrivateCredentials";
  permission javax.security.auth.AuthPermission "setReadOnly";
  permission java.lang.RuntimePermission "setContextClassLoader";
  permission java.net.SocketPermission "*", "listen,resolve";
  permission java.lang.reflect.ReflectPermission "suppressAccessChecks";
};
```

Running elasticsearch: 
`"version" : {    "number" : "2.1.1",`

Then installed this zipfile: 
https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.2.1.2/elasticsearch-transport-couchbase-2.2.1.2.zip

Set the couchbase values for port:9091 and my couchbase username/password num_vbuckets and fired things up. 

Busted for both java.policy and java.security files in $JAVA_HOME/lib/security folder. I do not have user specific overrides for either of these files.   

```
Starting transport-couchbase plugin server on address:/0.0.0.0 port: 9091 publish address: /172.17.0.2
Exception in thread "main" BindHttpException[Failed to bind to [9091]]; nested: AccessControlException[access denied ("javax.security.auth.AuthPermission" "modifyPrincipals")];
Likely root cause: java.security.AccessControlException: access denied ("javax.security.auth.AuthPermission" "modifyPrincipals")
    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
    at java.security.AccessController.checkPermission(AccessController.java:884)
    at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
    at javax.security.auth.Subject$SecureSet.add(Subject.java:1110)
    at java.util.Collections$SynchronizedCollection.add(Collections.java:2035)
    at org.eclipse.jetty.security.MappedLoginService.putUser(MappedLoginService.java:185)
    at com.couchbase.capi.CAPIServer.basicAuth(CAPIServer.java:142)
    at com.couchbase.capi.CAPIServer.<init>(CAPIServer.java:74)
    at org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl$1$1.run(CouchbaseCAPITransportImpl.java:221)
    at org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl$1$1.run(CouchbaseCAPITransportImpl.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl$1.onPortNumber(CouchbaseCAPITransportImpl.java:217)
    at org.elasticsearch.common.transport.PortsRange.iterate(PortsRange.java:58)
    at org.elasticsearch.transport.couchbase.capi.CouchbaseCAPITransportImpl.doStart(CouchbaseCAPITransportImpl.java:214)
    at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
    at org.elasticsearch.transport.couchbase.CouchbaseCAPI.doStart(CouchbaseCAPI.java:42)
    at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
    at org.elasticsearch.node.Node.start(Node.java:242)
    at org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:221)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:287)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

Other things:

```
java -version
openjdk version "1.8.0_66-internal"
```

Plugin installed ok: 

```
Verifying https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.2.1.2/elasticsearch-transport-couchbase-2.2.1.2.zip checksums if available ...
Downloading .DONE
Installed transport-couchbase into /usr/share/elasticsearch/plugins/transport-couchbase
```

**Comment by erik-etops** [comment]
So for now it looks like I've overcome this with the following nonsense: 

```
grant codeBase "file:/usr/share/elasticsearch/plugins/transport-couchbase/-" {
        permission javax.security.auth.AuthPermission "modifyPrincipals";
        permission javax.security.auth.AuthPermission "modifyPrivateCredentials";                                                        
        permission javax.security.auth.AuthPermission "setReadOnly";                                                                     
        permission java.lang.RuntimePermission "setContextClassLoader";                                                                  
        permission java.net.SocketPermission "*", "listen,resolve";                                                                      
        permission java.lang.reflect.ReflectPermission "suppressAccessChecks";                                                           
};                                                                                                                                       

grant codeBase "file:/usr/share/elasticsearch/plugins/-" {
        permission java.security.AllPermission;
};
```

**Comment by Branor** [comment]
Try using "file:/usr/share/elasticsearch/plugins/transport-couchbase/*" (note the * rather than - at the end), which should make the policy apply to all files in that folder.

**Comment by dnault** [comment]
Hi erik-etops, 

Are you still having trouble granting permissions, or did you figure it out? Of course one way is to upgrade to ES 2.2+ which handles plugin permissions in a much friendlier way.

Thanks,
David

**Comment by dnault** [comment]
Closing due to inactivity. Please let me know if the issue remains.
