### ISSUE TITLE
ES not recognizing couchbase lines in config.

### ISSUE THREAD

**Issue by jcspino** [couchbaselabs/elasticsearch-transport-couchbase#141]
I went through the install process but after adding the couchbase lines to my elasticsearch.yml file I cannot get ES to start. The error indicates it does not recognize the configuration lines. The contents of my config file are attached as well as my cluster details. Thank you for any help and let me know if you need any more information. 

<____ERROR______>
[elasticsearch.txt](https://github.com/couchbaselabs/elasticsearch-transport-couchbase/files/556377/elasticsearch.txt)
[cluster info.txt](https://github.com/couchbaselabs/elasticsearch-transport-couchbase/files/556378/cluster.info.txt)

[madmin@mbatless02 elasticsearch]$ bin/elasticsearch -d -p pid
[madmin@mbatless02 elasticsearch]$ Exception in thread "main" SettingsException[Failed to load settings from [elasticsearch.yml]]; nested: ElasticsearchParseException[malformed, expected end of settings but encountered additional content starting at line number: [95], column number: [1]]; nested: ParserException[expected '<document start>', but found BlockMappingStart
 in 'reader', line 95, column 1:
    couchbase.password: password1
    ^
];
Likely root cause: expected '<document start>', but found BlockMappingStart
 in 'reader', line 95, column 1:
    couchbase.password: password1
    ^

```
    at com.fasterxml.jackson.dataformat.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce(ParserImpl.java:225)
    at com.fasterxml.jackson.dataformat.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
    at com.fasterxml.jackson.dataformat.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
    at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:342)
    at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:53)
    at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:72)
    at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:45)
    at org.elasticsearch.common.settings.loader.YamlSettingsLoader.load(YamlSettingsLoader.java:46)
    at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1074)
    at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:1061)
    at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:88)
    at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:107)
    at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:100)
    at org.elasticsearch.bootstrap.BootstrapCLIParser.<init>(BootstrapCLIParser.java:48)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:241)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

Refer to the log for complete error details.

**Comment by dnault** [comment]
First off, apologies for the belated response. Are you still having trouble, or did you figure it out?

One thing to be aware of is that the plugin must be installed *before* starting Elasticsearch with the additional config, otherwise ES will complain that the config is unrecognized.

Another thing to try would be to run the config file through a YAML validator to check for syntax errors.

**Comment by jcspino** [comment]
I figured this out but unfortunately I don't remember what the resolution was. 

Thanks for getting back to me.
