### ISSUE TITLE
Support for ES 5.0.2

### ISSUE THREAD

**Issue by zzvara** [couchbaselabs/elasticsearch-transport-couchbase#145]
Is this on the road map? Would it be a great deal of work to move to 5.0.2 from 5.0.0-alpha4?

**Comment by courtneycouch** [comment]
I'm also curious if this is coming anytime soon

**Comment by monzonj** [comment]
+1

**Comment by baalthazaar1** [comment]
+1

**Comment by baalthazaar1** [comment]
+1

**Comment by korczis** [comment]
Any updates?

**Comment by korczis** [comment]
@mschoch @Branor can you shed some light, please?

**Comment by WillGardella** [comment]
Copying my response from a different thread, this issue is nearly a duplicate with a different follower list. I talked to @branor and 5.1 support is planned for Q1 2017. The reason it's taking a while is that ES removed an API that we formerly used to synchronize plugin instances, which we need to do to make sure vBuckets are mapped appropriately across the cluster. There's no replacement for that API and ES is not bringing it back, so we need to figure out how to move forward with the reduced functionality. This would probably mean that your cluster is created appropriately but would need to be restarted when you add or remove nodes. There may be other impacts that are less obvious, too, but that's the major one. This makes the effort greater and will require new tests as well.

**Comment by zzvara** [comment]
@WillGardella Thanks for the update, sorry to hear that we've got troubles.

**Comment by Branor** [comment]
We now have a pre-release version of the plugin for ES 5.2.1 available here: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/v.2.5.2.1
It's fully functional, but hasn't made it through the full QA process at Couchbase yet.

(If you need a build for a lower version of ES, let me know. The code is backwards compatible to all ES 5.x versions, so it's just a matter of building a version-specific plugin package.)

**Comment by korczis** [comment]
I will test this tomorrow and share the feedback. Great work. Thanks.

**Comment by korczis** [comment]
I am experiencing problems with x-pack. I am not sure if this is related to elasticsearch-transport-couchbase

```
ESC[36melasticsearch_1  |ESC[0m org.elasticsearch.ElasticsearchSecurityException: action [indices:admin/exists] is unauthorized for user [_system]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.support.Exceptions.authorizationError(Exceptions.java:45) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authz.AuthorizationService.denialException(AuthorizationService.java:420) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authz.AuthorizationService.denial(AuthorizationService.java:391) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:145) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$authorizeRequest$4(SecurityActionFilter.java:189) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:127) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:121) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:102) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.authorizeRequest(SecurityActionFilter.java:204) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$3(SecurityActionFilter.java:180) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:56) ~[elasticsearch-5.2.1.jar:5.2.1]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$handleNullToken$11(AuthenticationService.java:310) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.handleNullToken(AuthenticationService.java:320) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.consumeToken(AuthenticationService.java:247) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$extractToken$5(AuthenticationService.java:223) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.extractToken(AuthenticationService.java:236) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$0(AuthenticationService.java:184) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$2(AuthenticationService.java:201) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:213) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:180) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:142) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:114) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.applyInternal(SecurityActionFilter.java:179) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:139) ~[?:?]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:171) ~[elasticsearch-5.2.1.jar:5.2.1]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:145) ~[elasticsearch-5.2.1.jar:5.2.1]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:87) ~[elasticsearch-5.2.1.jar:5.2.1]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:75) ~[elasticsearch-5.2.1.jar:5.2.1]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:64) ~[elasticsearch-5.2.1.jar:5.2.1]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403) ~[elasticsearch-5.2.1.jar:5.2.1]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1226) ~[elasticsearch-5.2.1.jar:5.2.1]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80) ~[elasticsearch-5.2.1.jar:5.2.1]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54) ~[elasticsearch-5.2.1.jar:5.2.1]
ESC[36melasticsearch_1  |ESC[0m         at org.elasticsearch.transport.couchbase.capi.ElasticSearchCouchbaseBehavior.getBucketUUID(ElasticSearchCouchbaseBehavior.java:204) ~[elasticsearch-transport-couchbase-2.5.2.1.jar:?]
ESC[36melasticsearch_1  |ESC[0m         at com.couchbase.capi.servlet.BucketMapServlet.formatBuckets(BucketMapServlet.java:121) ~[couchbase-capi-server-1.6.0.jar:?]
ESC[36melasticsearch_1  |ESC[0m         at com.couchbase.capi.servlet.BucketMapServlet.executeBucketsRequest(BucketMapServlet.java:109) ~[couchbase-capi-server-1.6.0.jar:?]
ESC[36melasticsearch_1  |ESC[0m         at com.couchbase.capi.servlet.BucketMapServlet.doGet(BucketMapServlet.java:79) ~[couchbase-capi-server-1.6.0.jar:?]
ESC[36melasticsearch_1  |ESC[0m         at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[javax.servlet-api-3.1.0.jar:3.1.0]
:
```
