### ISSUE TITLE
ERROR: Unknown plugin elasticsearch-transport-couchbase-master.zip

### ISSUE THREAD

**Issue by nintyuui** [couchbaselabs/elasticsearch-transport-couchbase#150]
./elasticsearch-plugin install elasticsearch-transport-couchbase-master.zip
A tool for managing installed elasticsearch plugins

Commands
--------
list - Lists installed elasticsearch plugins
install - Install a plugin
remove - Removes a plugin from elasticsearch

Non-option arguments:
command              

Option         Description        
------         -----------        
-h, --help     show help          
-s, --silent   show minimal output
-v, --verbose  show verbose output
ERROR: Unknown plugin elasticsearch-transport-couchbase-master.zip

I also follow the wiki to try:
bin/elasticsearch-plugin install https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.5.2.1/elasticsearch-transport-couchbase-2.5.2.1.zip
-> Downloading https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.5.2.1/elasticsearch-transport-couchbase-2.5.2.1.zip
Exception in thread "main" java.io.FileNotFoundException: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.5.2.1/elasticsearch-transport-couchbase-2.5.2.1.zip
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:279)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:254)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:210)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:195)
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
Caused by: java.io.FileNotFoundException: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.5.2.1/elasticsearch-transport-couchbase-2.5.2.1.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2982)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:398)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:278)
	... 9 more

**Comment by korczis** [comment]
This works for me:

```
elasticsearch-plugin install file:///usr/share/elasticsearch/my-plugins/elasticsearch-transport-couchbase-2.5.1.1.zip
```

**Comment by vishal1kumar** [comment]
you need to do it like this:
./elasticsearch-plugin install file:///<path of the zip file>/elasticsearch-transport-couchbase-master.zip
