### ISSUE TITLE
Request: Update for ES 5.3.0

### ISSUE THREAD

**Issue by AlmightyOatmeal** [couchbaselabs/elasticsearch-transport-couchbase#161]
I see there is a build for ES 5.4.0 but some of us are running 5.3.0; can I get a built for ES 5.3.0?

```
$ curl http://localhost:9200
{
  "name" : "vonavi-vm-es-01",
  "cluster_name" : "vonavi",
  "cluster_uuid" : "jQPqybv5QLqiJySk3X2bQg",
  "version" : {
    "number" : "5.3.0",
    "build_hash" : "3adb13b",
    "build_date" : "2017-03-23T03:31:50.652Z",
    "build_snapshot" : false,
    "lucene_version" : "6.4.1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by Branor** [comment]
It's right here: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/tag/2.5.3.0

**Comment by AlmightyOatmeal** [comment]
@Branor,

```
$ sudo bin/elasticsearch-plugin install https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.5.3.0/elasticsearch-transport-couchbase-2.5.3.0.zip
-> Downloading https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.5.3.0/elasticsearch-transport-couchbase-2.5.3.0.zip
Exception in thread "main" java.io.FileNotFoundException: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.5.3.0/elasticsearch-transport-couchbase-2.5.3.0.zip
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:275)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:250)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:206)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:192)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:58)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
Caused by: java.io.FileNotFoundException: https://github.com/couchbaselabs/elasticsearch-transport-couchbase/releases/download/v2.5.3.0/elasticsearch-transport-couchbase-2.5.3.0.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:2982)
	at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
	at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
	at java.net.URLConnection.getContentLength(URLConnection.java:485)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentLength(HttpsURLConnectionImpl.java:398)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:274)
	... 9 more
```

Looking at the URL based on what the README says on the front page, it depicts `/download/v2.5.3.0/` but the link you mentioned lacks the "v" so it is `/download/2.5.3.0/`; it looks like the build is in the wrong path or the README is wrong :(
