### ISSUE TITLE
Using elasticsearch-transport-couchbase plugin in a cluster with X-Pack Security

### ISSUE THREAD

**Issue by yzargari** [couchbaselabs/elasticsearch-transport-couchbase#170]
Hello,
I have an Elasticsearch 1.7 cluster with shield installed on it and the elasticsearch-transport-couchbase plugin. It works OK if I add credentials in the elasticsearch.yml file for shield.user (set to "username:password") .

Now I'm working on getting the same setup running on Elasticsearch 5.5 with X-Pack security. The thing is that it doesn't support the shield.user property in the YAML file and I'm not sure if and how it is possible to setup credentials for the couchbase ingestion plugin.

Is this even supported? What's the correct setup?
Thanks!

**Comment by yzargari** [comment]
@Branor - can you shed some light on this?

**Comment by tata2000** [comment]
Can please anyone look into this issue?

**Comment by tata2000** [comment]
Here are some logs from elasticsearch side:

[2017-08-23T11:46:01,758][DEBUG][o.e.t.c.c.CouchbaseCAPITransportImpl] [i-038dcb4e4a2c6bad5-elk5-node] Found transport-couchbase running on: <elastic_ip>:9091
[2017-08-23T11:46:01,777][DEBUG][o.e.t.c.c.CouchbaseCAPITransportImpl] [i-038dcb4e4a2c6bad5-elk5-node] bucket UUID not in cache, looking up
[2017-08-23T11:46:01,779][WARN ][o.e.j.s.ServletHandler   ] /pools/default/buckets
org.elasticsearch.ElasticsearchSecurityException: action [indices:admin/exists] is unauthorized for user [_system]
	at org.elasticsearch.xpack.security.support.Exceptions.authorizationError(Exceptions.java:45) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.denialException(AuthorizationService.java:459) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.denial(AuthorizationService.java:430) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:157) ~[?:?]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$authorizeRequest$4(SecurityActionFilter.java:190) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:127) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:121) ~[?:?]
	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:103) ~[?:?]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.authorizeRequest(SecurityActionFilter.java:205) ~[?:?]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$applyInternal$3(SecurityActionFilter.java:181) ~[?:?]
	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:59) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$handleNullToken$12(AuthenticationService.java:326) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.handleNullToken(AuthenticationService.java:336) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.consumeToken(AuthenticationService.java:258) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$extractToken$5(AuthenticationService.java:234) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.extractToken(AuthenticationService.java:247) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$authenticateAsync$0(AuthenticationService.java:194) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lambda$lookForExistingAuthentication$2(AuthenticationService.java:212) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.lookForExistingAuthentication(AuthenticationService.java:224) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.authenticateAsync(AuthenticationService.java:190) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService$Authenticator.access$000(AuthenticationService.java:147) ~[?:?]
	at org.elasticsearch.xpack.security.authc.AuthenticationService.authenticate(AuthenticationService.java:118) ~[?:?]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.applyInternal(SecurityActionFilter.java:180) ~[?:?]
	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.apply(SecurityActionFilter.java:140) ~[?:?]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:168) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:142) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:84) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:83) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:72) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1256) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54) ~[elasticsearch-5.4.1.jar:5.4.1]
	at org.elasticsearch.transport.couchbase.capi.ElasticSearchCouchbaseBehavior.getBucketUUID(ElasticSearchCouchbaseBehavior.java:204) ~[elasticsearch-transport-couchbase-2.5.4.1.jar:?]
	at com.couchbase.capi.servlet.BucketMapServlet.formatBuckets(BucketMapServlet.java:115) ~[couchbase-capi-server-1.6.2.jar:?]
	at com.couchbase.capi.servlet.BucketMapServlet.executeBucketsRequest(BucketMapServlet.java:104) ~[couchbase-capi-server-1.6.2.jar:?]
	at com.couchbase.capi.servlet.BucketMapServlet.doGet(BucketMapServlet.java:74) ~[couchbase-capi-server-1.6.2.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[jetty-servlet-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) [jetty-servlet-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:513) [jetty-security-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.Server.handle(Server.java:523) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.13.v20161014.jar:9.3.13.v20161014]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by chenbekor** [comment]
@Branor this ticket is supper urgent can you please look at this issue and report back on how to approach this issue? I don't mind contributing a pull request I just need some guidance on where to patch the plugin.

**Comment by dnault** [comment]
Because the Elasticsearch plugin interacts directly with the Elasticsearch API, it acts as the [internal user](https://www.elastic.co/guide/en/x-pack/current/setting-up-authentication.html#internal-users) named "_system".

I wonder if it's possible to apply the [built in "superuser" role](https://www.elastic.co/guide/en/x-pack/current/built-in-roles.html#built-in-roles) to the internal `_system` user, and whether that would resolve the issue.

**Comment by tata2000** [comment]
@dnault 
I have checked that with elasticsearch support, and their answer were that couchbase plugin does not use the API properly and it is need to be rewritten to supply username and password.
and _system user can not be granted more privileges.

**Comment by dnault** [comment]
@tata2000 Thanks, that's useful information. I've started a thread on the ES forums to figure out what the Couchbase plugin needs to do in order to authenticate properly:

https://discuss.elastic.co/t/how-should-a-plugin-authenticate-with-x-pack/108300

If you'd like to ask your support contact to respond over there, it might expedite the process.

**Comment by tata2000** [comment]
hi @dnault 

here is the information that I have received from ES support back when i have asked their help on making it work:

> The "_system" user is indeed used internally by Elasticsearch when a TransportClient is used without being properly configured to interact with a cluster protected by Shield/X-Pack Security.
> 
> Unfortunately there is no way to change it's privileges and the only supported way to fix this issue is to use the java PreBuiltXPackTransportClient class so you can properly set the "xpack.security.user". See https://www.elastic.co/guide/en/x-pack/current/java-clients.html for more information.
> 
> Lastly, keep in mind that the TransportClient will be deprecated in 6.0 and eventually will be completely replaced by the Java REST Client (see https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/index.html for more information)
>

**Comment by tata2000** [comment]
@dnault also asked ES team to respond on the thread you have started.

**Comment by dnault** [comment]
Quick update: X-Pack requires talking to Elasticsearch over HTTP instead of using the TransportClient to directly call the internal APIs.

We're building a new version of the connector for ES 6.x that will be compatible with X-Pack (see #180). The new connector will also likely be compatible with ES 5.x, although we're trimming the feature set to match what's supported by ES 6 (no parent-child relationships, etc).

That's the short-term plan. After the new connector ships, we *might* go back and look at adding X-Pack support to the current connector, but ultimately we'd like to encourage everyone to migrate to ES 6.
