### ISSUE TITLE
Replication Errors

### ISSUE THREAD

**Issue by czmdb** [couchbaselabs/elasticsearch-transport-couchbase#59]
Hi,

I am using the transport plugin 2.0 to index documents from  a couchbase (2.5.1)  3 Nodes cluster to an ES cluster 1.1.0 (3 Nodes).
 The number of docs is  relatively small (5000) 
Shortly after starting the XDCR replicator I am getting errors such as :

[xdcr:error,2015-01-07T11:14:20.640,ns_1@37.59.4.109:<0.2404.2153>:xdc_vbucket_rep:terminate:381]Replication (CAPI mode) `330487fb31ae3633bd19f43d4580cd2e/stage1/stage1` (`stage1/332` -> `http://*****@46.105.102.32:9091/stage1%2f332%3bd49b4d193469491f86f04463be174c08`) failed: {http_request_failed,"POST",                 "http://Administrator:*****@46.105.102.32:9091/stage1%2f332%3bd49b4d193469491f86f04463be174c08/_revs_diff",{error,{code,500}}} 

and on the ES side I can see  :

[2015-01-07 11:22:54,693][ERROR][transport.couchbase.capi ] [elastic_node1] Unable to parse decoded base64 data as JSON, indexing stub for id: _sync:seq
[2015-01-07 11:22:54,693][ERROR][transport.couchbase.capi ] [elastic_node1] Body was: 6027 Parse error was: org.codehaus.jackson.map.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of VALUE_NUMBER_INT token

When I run queries on ES I am missing half of the results .. 
Do you have any idea on how to troubleshoot this ?  I cannot figure out what's wrong with the documents . These are being updated by a CB Sync Gateway , could it be that they require a special field mapping ?
In the elastic config I tried index.mapping.ignore_malformed: true but that doesn't help

Thanks a lot for any help / suggestion

christian

**Comment by mschoch** [comment]
The error you see on the Couchbase side is fatal, and we need to know what is causing it on the ES side.

The message you pasted from the ES side is more information in nature, and not really an error.  It looks like there is a document in the bucket that is not JSON.  This is not related the error you see on the Couchbase side.

Are there any other errors in the ES log?

**Comment by czmdb** [comment]
Thanks for you help,

On the ES side, I am just getting that  same error I pasted , approx 1 every minute and ongoing .. and no other different errors.

You are saying there could be a doc that is no JSON in the bucket, in other words that some sort of corruption has occurred ? Should I try to restore a new empty bucket and start XDCR on it ?

**Comment by mschoch** [comment]
No, but sync gateway stores additional documents, beyond just your data.  I believe that not all of these documents are JSON.  I seem to recall that there is a sequence number document, that is just a single numerical value, and the Couchbase INCR operation is used to manipulate it.  Because that document is not JSON it cannot be indexed.

The reason you keep seeing it is that every time the value is incremented, XDCR will try to send the document again.  There is really no way to avoid this.

That said, this is not related to the problem you are seeing.  The failed _revs_diff means that replication for at least one vbucket has stopped.  This will result in missing data in the search index.

Can you post the entire log ES log somewhere?

**Comment by czmdb** [comment]
No problems about posting the ES log 
I have restarted ES in DEBUG mode , can I send it to your email ?

**Comment by mschoch** [comment]
Please send it to marty@couchbase.com.  Thanks

**Comment by mschoch** [comment]
Sorry for the delays, apparently the message you sent did not get through the corporate email.  Can you send it again this time to my gmail address?

**Comment by mschoch** [comment]
I reviewed the log you sent, and it doesn't appear to be from the node that reported the _revs_diff error (46.105.102.32).

Can you send me the ES log from that node?

**Comment by mschoch** [comment]
OK, I got the new log.  Unfortunately it looks like maybe the log rotated, as the log does not contain anything around the 2015-01-07T11:14:20.640 time period (where the original error on the Couchbase side was reported)

I do see some errors associated with _revs_diff though, so we can assume for now they are the same:

[2015-01-12 09:43:41,170][WARN ][org.eclipse.jetty.servlet.ServletHandler] /prod1%2f236%3b2ab66030488348f9ba03607828e02da0/_revs_diff
org.codehaus.jackson.JsonParseException: Invalid UTF-8 middle byte 0x2d61e972
 at [Source: [B@747dbe01; line: 1, column: 56]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
	at org.codehaus.jackson.impl.Utf8StreamParser._reportInvalidOther(Utf8StreamParser.java:2830)
	at org.codehaus.jackson.impl.Utf8StreamParser.addName(Utf8StreamParser.java:1821)
	at org.codehaus.jackson.impl.Utf8StreamParser.findName(Utf8StreamParser.java:1749)
	at org.codehaus.jackson.impl.Utf8StreamParser.parseLongFieldName(Utf8StreamParser.java:1373)
	at org.codehaus.jackson.impl.Utf8StreamParser.parseMediumFieldName(Utf8StreamParser.java:1323)
	at org.codehaus.jackson.impl.Utf8StreamParser._parseFieldName(Utf8StreamParser.java:1258)
	at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:495)
	at org.codehaus.jackson.map.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:299)
	at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:249)
	at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2732)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1935)
	at com.couchbase.capi.servlet.CAPIServlet.handleRevsDiff(CAPIServlet.java:334)
	at com.couchbase.capi.servlet.CAPIServlet.service(CAPIServlet.java:91)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:594)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:485)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:412)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:347)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:451)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:931)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)

I've never encountered this one before.  But it does help narrow things down a bit.  The _revs_diff response is mostly made up of your document IDs and Couchbase revision numbers.  So the most likely cause is that you have a document id that is not utf-8 encoded.  Strictly speaking Couchbase does not require utf-8 encoded keys, but many of the newer features likes Views and XDCR expect it.

There are 2 things to do:

1.  Review for any usual keys (possibly containing the byte sequence 0x2d61e972)
2.  Please add the lines:
transport.couchbase: TRACE
com.couchbase: TRACE

To the "logger" section of your logging.yml config file.  Then restart the node.

At the trace level I think we log the entire _revs_diff request and response, which should help us find the problematic ID.

**Comment by Branor** [comment]
Fixed in v2.1.1
