### ISSUE TITLE
urgent! bug in latest snapshot

### ISSUE THREAD

**Issue by chenbekor** [couchbaselabs/elasticsearch-transport-couchbase#74]
@Branor we are running against the latest snapshot and we are experiencing an issue. Maybe you can help us. Specifically, we are testing the feature that we added lately ("ignore deletes")

For some reason the initialization is ignoring the yml entry. Can you please check on your side?

here is how:

in the elasticsearch.yml file please add this line:
couchbase.ignore.delete: test1:test2:test3

now, when starting ES you should see the following debug print in the console:

[time][INFO ][transport.couchbase.capi ] [node name] Couchbase transport will ignore delete operations for this buckets: [test1,test2,test3]

What we are seeing (unfortunately) is this line:

Couchbase transport will ignore delete/expiration operations for these buckets: [] 

as you can see the array is empty which is bad because it means the parsing of the string (colon separated index names) is ignored...

your help is appreciated!

**Comment by Branor** [comment]
@chenbekor The configuration option is called "couchbase.ignoreDeletes" in the snapshot build, to be more consistent with other similar settings.
https://github.com/Branor/elasticsearch-transport-couchbase/releases/tag/v2.1.0-SNAPSHOT - scroll down to "Advanced Settings" for the description.

**Comment by chenbekor** [comment]
ok @Branor thanks for the update - my bad for not reading the updated source code/documentation. we are now facing a new issue - when using the ignoreDeletes feature the log starts to throw huge amount of exceptions:

when rolling back and not using ignoreDeletes  all is good. any clue why the SNAPSHOT version is not behaving nicely with this feature?

```java
org.elasticsearch.action.NoShardAvailableActionException: [test1][4] null
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.perform(TransportShardSingleOperationAction.java:175)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.onFailure(TransportShardSingleOperationAction.java:162)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.access$1300(TransportShardSingleOperationAction.java:116)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction$1.run(TransportShardSingleOperationAction.java:198)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.index.shard.IllegalIndexShardStateException: [test1][4] CurrentState[RECOVERING] operations only allowed when started/relocated
	at org.elasticsearch.index.shard.service.InternalIndexShard.readAllowed(InternalIndexShard.java:843)
	at org.elasticsearch.index.shard.service.InternalIndexShard.readAllowed(InternalIndexShard.java:834)
	at org.elasticsearch.index.shard.service.InternalIndexShard.get(InternalIndexShard.java:487)
	at org.elasticsearch.index.get.ShardGetService.innerGet(ShardGetService.java:193)
	at org.elasticsearch.index.get.ShardGetService.get(ShardGetService.java:104)
	at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:97)
	at org.elasticsearch.action.get.TransportGetAction.shardOperation(TransportGetAction.java:43)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction$1.run(TransportShardSingleOperationAction.java:195)
	... 3 more
[2015-03-11 08:01:54,169][WARN ][org.eclipse.jetty.servlet.ServletHandler] /pools/default/buckets
org.elasticsearch.action.NoShardAvailableActionException: [test1][4] null
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.perform(TransportShardSingleOperationAction.java:175)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.onFailure(TransportShardSingleOperationAction.java:162)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction.access$1300(TransportShardSingleOperationAction.java:116)
	at org.elasticsearch.action.support.single.shard.TransportShardSingleOperationAction$AsyncSingleAction$1.run(TransportShardSingleOperationAction.java:198)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
