### ISSUE TITLE
InvalidTypeNameException[mapping type name [_sync] can't start with '_']

### ISSUE THREAD

**Issue by atom992** [couchbaselabs/elasticsearch-transport-couchbase#96]
I am using couchbase server 3.1.0-1776 Enterprise Edition (build-1776) with sync gateway 1.1.0-28.
I am using elasticsearch-transport-couchbase-2.1.1 with elasticsearch 1.5.2.
In my elasticsearch.yml I included:
couchbase.keyFilter: org.elasticsearch.transport.couchbase.capi.RegexKeyFilter
couchbase.keyFilter.type: exclude
couchbase.keyFilter.keyFiltersRegex.sync: ^*sync.*$
couchbase.typeSelector: org.elasticsearch.transport.couchbase.capi.DelimiterTypeSelector

I want to transport doc without _sync* docs to elasticsearch. but I got the errors:
java.lang.RuntimeException: InvalidTypeNameException[mapping type name [_sync] can't start with '_']
java.lang.InterruptedException: sleep interrupted
	at org.elasticsearch.transport.couchbase.capi.ElasticSearchCAPIBehavior.bulkDocs(ElasticSearchCAPIBehavior.java:549)
	at com.couchbase.capi.servlet.CAPIServlet.handleBulkDocs(CAPIServlet.java:529)
	at com.couchbase.capi.servlet.CAPIServlet.service(CAPIServlet.java:89)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:594)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:485)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1065)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:412)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:192)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:999)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:351)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:451)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:931)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
	at java.lang.Thread.run(Thread.java:745)

**Comment by atom992** [comment]
I review the log,the more detail is as following:

[2015-09-08 00:50:10,207][TRACE][transport.couchbase.capi ] [Benjamin Jacob Grimm] ignoreDelete = false
[2015-09-08 00:50:10,207][TRACE][transport.couchbase.capi ] [Benjamin Jacob Grimm] Bulk doc entry is [{meta={id=_sync:rev:GST:b22d5dd1-0323-46c3-887b-99dabfdd8591:34:1-8850ef2006a40f0af2f69e797d1cf3fa, rev=2-00000330c303113f0000000000000000, att_reason=invalid_json, expiration=0, flags=0, deleted=true}, base64=}]
[2015-09-08 00:50:10,207][TRACE][transport.couchbase.capi ] [Benjamin Jacob Grimm] ignoreDelete = false
[2015-09-08 00:50:10,207][TRACE][transport.couchbase.capi ] [Benjamin Jacob Grimm] Selecting type _sync for document _sync:rev:GST:b22d5dd1-0323-46c3-887b-99dabfdd8591:34:1-8850ef2006a40f0af2f69e797d1cf3fa in index dev4test
[2015-09-08 00:50:10,207][TRACE][transport.couchbase.capi ] [Benjamin Jacob Grimm] Bulk doc entry is [{meta={id=_sync:rev:GST::34:1-a162d6f6c5a0411cc1b252a754bccfb7, rev=2-0000033088c08f060000000000000000, att_reason=invalid_json, expiration=0, flags=0, deleted=true}, base64=}]
[2015-09-08 00:50:10,208][TRACE][transport.couchbase.capi ] [Benjamin Jacob Grimm] Selecting type _sync for document _sync:rev:GST::34:1-a162d6f6c5a0411cc1b252a754bccfb7 in index dev4test
[2015-09-08 00:50:10,208][DEBUG][action.bulk              ] [Benjamin Jacob Grimm] [dev4test][4] failed to execute bulk item (delete) delete {[dev4test][_sync][_sync:rev:GST:b22d5dd1-0323-46c3-887b-99dabfdd8591:34:1-8850ef2006a40f0af2f69e797d1cf3fa]}
org.elasticsearch.indices.InvalidTypeNameException: mapping type name [_sync] can't start with '_'
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:319)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:307)
        at org.elasticsearch.index.mapper.MapperService.documentMapperWithAutoCreate(MapperService.java:467)
        at org.elasticsearch.index.shard.IndexShard.prepareDelete(IndexShard.java:510)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardDeleteOperation(TransportShardBulkAction.java:457)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:205)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:515)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:422)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2015-09-08 00:50:10,208][DEBUG][action.bulk              ] [Benjamin Jacob Grimm] [dev4test][4] failed to execute bulk item (delete) delete {[dev4test][_sync][_sync:rev:GST:34:1-a162d6f6c5a0411cc1b252a754bccfb7]}
org.elasticsearch.indices.InvalidTypeNameException: mapping type name [_sync] can't start with '_'
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:319)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:307)
        at org.elasticsearch.index.mapper.MapperService.documentMapperWithAutoCreate(MapperService.java:467)
        at org.elasticsearch.index.shard.IndexShard.prepareDelete(IndexShard.java:510)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardDeleteOperation(TransportShardBulkAction.java:457)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:205)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:515)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:422)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

 and I also review the code:
https://github.com/couchbaselabs/elasticsearch-transport-couchbase/blob/master/src/main/java/org/elasticsearch/transport/couchbase/capi/ElasticSearchCAPIBehavior.java#L339-L348

I doubt the problem is here. could you please review the code?

**Comment by dnault** [comment]
Version 4 of the connector offers a default configuration that exclude these sync metadata documents.
